name: Run Tests on Push

on:
  workflow_dispatch:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Specify the desired Java version
          distribution: 'zulu'

      - name: setup FFMPEG
        uses: FedericoCarboni/setup-ffmpeg@v3.1

      - name: Build with Gradle and run tests
        run: ./gradlew build
